export const RIGHTS = {
  COMPANY: {
    ADMIN: 'ADMIN',
    VIEWER: 'VIEWER',
    TASK_CREATOR: 'TASK_CREATOR',
    TASK_VIEWER: 'TASK_VIEWER',
    TASK_MODERATOR: 'TASK_MODERATOR',
  },
  COMPANY_OBJECTS: {
    ADMIN: 'ADMIN',
    VIEWER: 'VIEWER',
    TASK_CREATOR: 'TASK_CREATOR',
    TASK_MODERATOR: 'TASK_MODERATOR',
    TASK_VIEWER: 'TASK_VIEWER',
  },
};
